<?php

declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
                           ->in('src')
;

$config = new PhpCsFixer\Config();

return $config->setRules([
    // PSR1, PSR2 and Symfony
    'encoding'                          => true,
    'full_opening_tag'                  => true,
    'blank_line_after_namespace'        => true,
    'elseif'                            => true,
    'function_declaration'              => true,
    'indentation_type'                  => true,
    'line_ending'                       => true,
    'constant_case'                     => ['case' => 'lower'],
    'lowercase_keywords'                => true,
    'no_break_comment'                  => true,
    'no_closing_tag'                    => true,
    'no_spaces_after_function_name'     => true,
    'no_spaces_inside_parenthesis'      => true,
    'no_trailing_whitespace'            => true,
    'no_trailing_whitespace_in_comment' => true,
    'single_blank_line_at_eof'          => true,
    'single_import_per_statement'       => true,
    'single_line_after_imports'         => true,
    'switch_case_semicolon_to_colon'    => true,
    'switch_case_space'                 => true,
    'visibility_required'               => true,

    'binary_operator_spaces'                      => true,
    'class_attributes_separation'                 => ['elements' => ['method' => 'one']],
    'class_definition'                            => [
        'multi_line_extends_each_single_line' => true,
        'single_item_single_line'             => true,
    ],
    'declare_equal_normalize'                     => true,
    'function_typehint_space'                     => true,
    'include'                                     => true,
    'lowercase_cast'                              => true,
    'magic_constant_casing'                       => true,
    'method_argument_space'                       => true,
    'native_function_casing'                      => true,
    'new_with_braces'                             => true,
    'no_blank_lines_after_class_opening'          => true,
    'no_blank_lines_after_phpdoc'                 => true,
    'no_empty_comment'                            => true,
    'no_empty_phpdoc'                             => true,
    'no_empty_statement'                          => true,
    'no_leading_import_slash'                     => true,
    'no_leading_namespace_whitespace'             => true,
    'no_mixed_echo_print'                         => ['use' => 'echo'],
    'no_multiline_whitespace_around_double_arrow' => true,
    'no_short_bool_cast'                          => true,
    'no_spaces_around_offset'                     => true,
    'no_trailing_comma_in_list_call'              => true,
    'no_trailing_comma_in_singleline_array'       => true,
    'no_unneeded_curly_braces'                    => true,
    'no_unused_imports'                           => true,
    'no_whitespace_before_comma_in_array'         => true,
    'no_whitespace_in_blank_line'                 => true,
    'normalize_index_brace'                       => true,
    'object_operator_without_whitespace'          => true,
    'php_unit_fqcn_annotation'                    => true,
    'phpdoc_annotation_without_dot'               => true,
    'phpdoc_indent'                               => true,
    'phpdoc_no_access'                            => true,
    'phpdoc_no_empty_return'                      => true,
    'phpdoc_no_package'                           => true,
    'phpdoc_no_useless_inheritdoc'                => true,
    'phpdoc_return_self_reference'                => true,
    'phpdoc_scalar'                               => true,
    'phpdoc_single_line_var_spacing'              => true,
    'phpdoc_trim'                                 => true,
    'phpdoc_types'                                => true,
    'phpdoc_var_without_name'                     => true,
    'protected_to_private'                        => true,
    'return_type_declaration'                     => true,
    'semicolon_after_instruction'                 => true,
    'short_scalar_cast'                           => true,
    'single_blank_line_before_namespace'          => true,
    'single_class_element_per_statement'          => true,
    'single_line_comment_style'                   => [
        'comment_types' => ['hash'],
    ],
    'single_quote'                                => true,
    'space_after_semicolon'                       => [
        'remove_in_empty_for_expressions' => true,
    ],
    'standardize_increment'                       => true,
    'standardize_not_equals'                      => true,
    'ternary_operator_spaces'                     => true,
    'trailing_comma_in_multiline'                 => ['elements' => ['arrays']],
    'trim_array_spaces'                           => true,
    'unary_operator_spaces'                       => true,
    'whitespace_after_comma_in_array'             => true,

    // exceptions
    'increment_style'                             => ['style' => 'post'],
    'blank_line_after_opening_tag'                => false,
    'blank_line_before_statement'                 => false,
    'cast_spaces'                                 => false,
    'concat_space'                                => ['spacing' => 'one'],
    'no_singleline_whitespace_before_semicolons'  => false,
    'phpdoc_align'                                => false,
    'phpdoc_separation'                           => false,
    'phpdoc_summary'                              => false,
    'yoda_style'                                  => false,
    'phpdoc_to_comment'                           => false,
    'phpdoc_no_alias_tag'                         => false,
    'general_phpdoc_tag_rename'                   => false,
    'phpdoc_inline_tag_normalizer'                => false,
    'phpdoc_tag_type'                             => false,
    'no_unneeded_control_parentheses'             => false, // works too aggressively with large structures
    'no_extra_blank_lines'                        => [
        'tokens' => [ // don't use curly_brace_block to allow splitting elseif blocks
            'extra',
            'parenthesis_brace_block',
            'square_brace_block',
            'throw',
            'use',
        ],
    ],

    // other base rules
    'no_useless_else'                             => true,
    'phpdoc_order'                                => false,
    'phpdoc_add_missing_param_annotation'         => [
        'only_untyped' => false,
    ],
    'multiline_whitespace_before_semicolons'      => false,
    'ordered_imports'                             => false,
    'array_syntax'                                => ['syntax' => 'short'],
    'general_phpdoc_annotation_remove'            => ['annotations' => ['author', 'namespace', 'date', 'inheritdoc', 'package']],
    'header_comment'                              => ['header' => ''],
    'heredoc_to_nowdoc'                           => true,
    'linebreak_after_opening_tag'                 => true,
    'no_useless_return'                           => true,
    'strict_comparison'                           => false,
    'strict_param'                                => false,
    'ordered_class_elements'                      => [
        'order' => [
            'use_trait',
            'constant',
            'property_static',
            'property',
            'construct',
            'destruct',
            'magic',
            'method_static',
            'method',
        ],
    ],
])
              ->setFinder($finder)
;
